######################################################################
#  Project
######################################################################

BINARY		= roguelike1d
SRCFILES	= main.c

all: elf bin

include ../../Makefile.incl

# End
