######################################################################
#  Project
######################################################################

BINARY		= roguelike1d
SRCFILES	= \
	debounce.c \
	enemy.c \
	game.c \
	main.c \
	player.c \
	TM1638.c \
	TM1638_platform.c

all: elf bin

include ../../Makefile.incl

# End
