######################################################################
#  Project
######################################################################

BINARY		= roguelike1d
SRCFILES	= \
	main.c \
	TM1638_platform.c \
	TM1638.c

all: elf bin

include ../../Makefile.incl

# End
